{% set version = "0.4.6.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rlist
  version: {{ version|replace("-", "_") }}

source:
  fn: rlist_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/rlist_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rlist/rlist_{{ version }}.tar.gz
  sha256: ebde658d897c8a27a90ebb892b9e2bad15e2ad75557a7352fb08cbb5604e0997

build:
  noarch: generic
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-xml
    - r-data.table
    - r-jsonlite
    - r-yaml
  run:
    - r-base
    - r-xml
    - r-data.table
    - r-jsonlite
    - r-yaml

test:
  commands:
    - $R -e "library('rlist')"           # [not win]
    - "\"%R%\" -e \"library('rlist')\""  # [win]

about:
  home: https://renkun.me/rlist, https://github.com/renkun-ken/rlist, https://renkun.me/rlist-tutorial
  license: MIT
  summary: Provides a set of functions for data manipulation with list objects, including mapping, filtering, grouping, sorting, updating, searching, and other useful functions. Most functions are designed to be pipeline friendly so that data processing with lists can be chained.
  license_family: MIT

  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE
extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
