travis:
  secure:
    BINSTAR_TOKEN: g6Q3a9gFuDyPrY1obnTq90I8lndpt0KboB0xitnnjHCHWxI5Humx2Yr750q7bITUD9nC1Qtr/2sTi7ehuKpfkKSVV+fj1T+rqScTLB4K9pVB85dKbkTBKznJe5FXQvYfCWvFEWPUD+YM1ZCNvGPYlGOgn0d4VJAsdl6oF86S0schjvSxPLVCDE1LWrWS+9IJ3Oo97BIS1fqqYvROzoneiick5NvYK8hl3sjTpyEK/IvvlctkO0SFHRTuQU1u449uNEZR1hygpnS56vXhRUe1XsN8zVh5xxaNqnMhH+ykZt8IpNztuTDLC8RhjdTRJyj2zW9UFmRgi12A+Q8r5hVR5Oh6EBQ2RfZjyu57/qpcUhuk4aREOhNQqX7nLNZ2tUGhfdc5NEccEwZd/XG+HgDdJIf4noZq24rWde+F5WyayV795n9Dw4L885AQfiotpmqeT30ADPFGM584/oyZuUtzrmcI9yPHVW7WG1teTTopSXpClbdfZhz+XWyfMGb5g85kMOgfh9whgvzPogfoEOsxSiRkhwMvHWRuRmawFTVBwlGrHJlOd/+agcwLJtGf2sV8fo/bAI9s4+rRcpAPiCKqBmEQ/fCnRHAkPAog7Wm3xUkJAiiPUY/5lrqSZAwnTmO6eg4osGGyGYTWHQo4OEXza8HyQEWU82lk5wwVkK/Lznc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
